name: robocore
description: A discord bot for CORE
version: 0.1.0
homepage: https://github.com/gokr/robocore.git
author: Göran Krampe <goran.krampe@gmail.com>

environment:
  sdk: '>=2.9.0 <3.0.0'

executables:  
  robocore: robocore

dependencies:
  http: ^0.12.0
  logging: ^0.11.3+2
  cron: ^0.2.3
  nyxx: ^1.0.2
  web3dart: ^1.2.3
  intl: ^0.16.1
  test: ^1.14.3
